### ISSUE TITLE
Draft.js 0.10.1 breaks plugin

### ISSUE THREAD

**Issue by tjunnone** [icelab/draft-js-block-breakout-plugin#10] opened 2017-05-10 15:05 UTC
Upgrading from Draft.js 0.10.0 to 0.10.1 seems to cause the following error when draft-js-block-breakout-plugin (1.0.3) is enabled, on pressing enter:

Uncaught TypeError: getEditorState is not a function at Object.handleReturn

Disabling the plugin, or downgrading Draft.js does remove the error.

**Comment by stevewillard** [comment] 2017-05-10 15:40
Just ran into this too.

**Comment by deep-c** [comment] 2017-05-13 09:33
I think its because the args passed to the handleReturn have changed, I managed to get it working locally by changing the arguments for handleReturn to `handleReturn (e, state, { getEditorState, setEditorState })`. Seems that the editorState is now passed in as the second argument?

**Comment by makenosound** [comment] 2017-05-14 22:58
Thanks for the extra info, @deep-c. I’m pushing through some deadlines over the next week or so, so I won’t likely get to look at this for a little while. Happy to look over a PR if any of you’d like to have a go at adjusting it!

**Comment by makenosound** [comment] 2017-05-21 22:51
Turns out [this is a regression in draft-js-plugins](https://github.com/draft-js-plugins/draft-js-plugins/issues/736). Closing.

**Closed as completed by makenosound** 2017-05-21 22:51 UTC

**Comment by deep-c** [comment] 2017-05-27 00:40
Hi, it turns out this was not a regression as per the latest comment in the thread above. Thanks

**Comment by makenosound** [comment] 2017-06-18 23:20
This has been fixed and released as v2.x
